### ISSUE TITLE
socket import problem

### ISSUE THREAD

**Issue by PFLeget** [sncosmo/sncosmo.github.io#4] opened 2015-10-30 17:29 UTC
Greetings,

When I do : 

import sncosmo
SALT=sncosmo.Model(source='salt2')

I have this issue:

/sw/lib/python2.7/site-packages/sncosmo/utils.pyc in _download_file(remote_url, target)
    276     # way, but for some reason in mysterious circumstances it doesn't. So
    277     # we'll just re-raise it here instead.
--> 278     except socket.timeout as e:
    279         raise URLError(e)
    280 

NameError: global name 'socket' is not defined

I check utils.py and there is no a "import socket" inside. 

This is that the problem or there is something else ?

Thanks a lot

**Comment by kbarbary** [comment] 2015-10-31 09:53
Thanks!

You probably meant to open this in http://github.com/sncosmo/sncosmo

This is a bug, which I just fixed in [this commit](https://github.com/sncosmo/sncosmo/commit/6b934228f7d3734223e4f21cb590a24d76e39511). However, it is just masking a problem with downloading a file. Usually this is due to some internet connectivity issue.

**Comment by kbarbary** [comment] 2015-10-31 09:54
Closing this issue. If you still have problems later when you're sure you have internet, open another issue in the main repository.

**Closed by kbarbary** 2015-10-31 09:54 UTC

**Comment by dannygoldstein** [comment] 2015-11-09 05:30
I get 

```pythonIn [2]: salt = sncosmo.Model(source='salt2')
---------------------------------------------------------------------------
URLError                                  Traceback (most recent call last)
<ipython-input-2-80c41e7d4663> in <module>()
----> 1 salt = sncosmo.Model(source='salt2')

/home/blanco/code/sncosmo/sncosmo/models.pyc in __init__(self, source, effects, effect_names, effect_frames)
   1086         self.param_names_latex = ['z', 't_0']
   1087         self._parameters = np.array([0., 0.])
-> 1088         self._source = get_source(source, copy=True)
   1089         self.description = None
   1090         self._effects = []

/home/blanco/code/sncosmo/sncosmo/models.pyc in get_source(name, version, copy)
     87             return name
     88     else:
---> 89         return cp(registry.retrieve(Source, name, version=version))
     90 
     91 

/home/blanco/code/sncosmo/sncosmo/registry.pyc in retrieve(data_class, name, version)
    194             regkey = (key[0], key[1], latest_version)
    195             func, args, meta = _loaders[regkey]
--> 196             _instances[regkey] = func(*args, name=name, version=latest_version)
    197             _instances[key] = _instances[regkey]
    198             return _instances[key]

/home/blanco/code/sncosmo/sncosmo/builtins.pyc in load_salt2model(relpath, name, version)
    174 
    175 def load_salt2model(relpath, name=None, version=None):
--> 176     abspath = get_abspath(relpath, name, version=version)
    177     return SALT2Source(modeldir=abspath, name=name, version=version)
    178 

/home/blanco/code/sncosmo/sncosmo/builtins.pyc in get_abspath(relpath, name, version)
    102         if url.endswith(".tar.gz") or url.endswith(".tar"):
    103             dirname = os.path.dirname(abspath)
--> 104             download_dir(url, dirname)
    105 
    106             # ensure that tarfile unpacked into the expected directory

/home/blanco/code/sncosmo/sncosmo/utils.pyc in download_dir(remote_url, dirname)
    318     # download file to buffer
    319     buf = io.BytesIO()
--> 320     _download_file(remote_url, buf)
    321     buf.seek(0)
    322 

/home/blanco/code/sncosmo/sncosmo/utils.pyc in _download_file(remote_url, target)
    245     # we'll just re-raise it here instead.
    246     except socket.timeout as e:
--> 247         raise URLError(e)
    248 
    249 

URLError: <urlopen error timed out>
```

**Comment by kbarbary** [comment] 2015-11-09 09:23
Seems like it is working as intended now. Can you check that you can get the URL ` http://supernovae.in2p3.fr/salt/lib/exe/fetch.php?media=salt2_model_data-2-4.tar.gz` using any other tool?

It would be nice if the attempted URL was printed before the error was raised.
